### ISSUE TITLE
Dropping a file on root folder produces Uncaught Error

### ISSUE THREAD

**Issue by pmkrawczyk** [davidbrochart/jupyterlab-remote-contents#3]
Hi,  have been using this repo (thank you for your work :-) to implement my own drive. Everything works fine, except for moving files to root folder (dropping), which produces:

```
Uncaught Error: ContentsManager: renaming files must occur within a Drive
    at t.ContentsManager.rename (index.js:291:19)
    at w.rename (manager.js:436:39)
    at d (dialogs.js:49:20)
    at v._evtDrop (crumbs.js:269:27)
    at v.handleEvent (crumbs.js:92:22)
    at e.dispatchDrop (index.es6.js:843:36)
    at r._evtPointerUp (index.es6.js:258:30)
    at r.handleEvent (index.es6.js:190:22)
```

Do you have any suggestions on how to solve or circumvent this issue?
Thanks!

**Comment by pmkrawczyk** [comment]
For now I monkey-patched the rename function in plugin init, which seems to work:

```
// Define our custom rename, to skip the drive check (gives an error when dropping onto root folder)
    async function customRename(this: any, path: string, newPath: string): Promise<any> {
      const [drive1, path1] = this._driveForPath(path);
      const [, path2] = this._driveForPath(newPath);
      
      // Disable the drive check, we only have one drive
      // if (drive1 !== drive2 && newPath !== '') {
      //     throw Error('ContentsManager: renaming files must occur within a Drive');
      // }
      return drive1.rename(path1, path2).then((contentsModel: Contents.IModel) => {
          return Object.assign(Object.assign({}, contentsModel), { path: this._toGlobalPath(drive1, path2) });
      });
    }
    // Override the original rename with our custom version
    (serviceManager.contents as any).rename = customRename.bind(serviceManager.contents);
```
But hopefully there is a clean solution ;-)
